### ISSUE TITLE
请问支持https需要使用openapi.baidu.com这个域名？

### ISSUE THREAD

**Issue by sleepholic** [Clouda-team/baiducdnstatic#127]
RT，http://cdn.code.baidu.com/ 网站上提供的apps.bdimg.com 这个域名直接用https访问证书有问题，显示证书是颁发给openapi.baidu.com的，在之前的[issue#76](https://github.com/Clouda-team/baiducdnstatic/issues/76) 里也看到有人提到引用openapi的这个域名，测试确实可用，但在网站上没有找到关于二者通用的相关描述，麻烦官方确认一下？

**Comment by dingquantracy** [comment]
是的 ，https站点可以使用 https://openapi.baidu.com 这个域名

**Comment by xuexb** [comment]
建议在官网明显位置写上`https`路径啊~
