### ISSUE TITLE
没有同步CDNJS的库。

### ISSUE THREAD

**Issue by cyberbox2001** [Clouda-team/baiducdnstatic#37]
根据百度静态资源公共库服务说明：不仅在Github开源库上接受任何人的提交请求，同时实时同步国外如CDNJS上优秀的开源库。
但iscroll库在360与CDNJ公共库也都有，百度却没有，可以提交一下吗？

**Comment by liyunfang** [comment]
是啊，百度的cdn不全。这个网站的比较全http://www.bootcdn.cn/  希望百度能多参考下这里的优秀资源

**Comment by hcoona** [comment]
已经 11 个月没有同步过了，百度这个 CDN 到底还有人维护没有？

**Comment by dingquantracy** [comment]
太夸张了吧  一般两周更新一次。

**Comment by hcoona** [comment]
`ref-cdnjs @ b4bf39f	update	11 months ago`
希望是我的幻觉
