### ISSUE TITLE
angular.js  404

### ISSUE THREAD

**Issue by panhb** [Clouda-team/baiducdnstatic#72]
http://apps.bdimg.com/libs/angular.js/1.1.4.0-beta.4/angular.min.js

**Comment by webx32** [comment]
http://apps.bdimg.com/libs/angular.js/1.4.0-beta.4/angular.min.js

是你输入错误

**Comment by panhb** [comment]
恩，谢谢提醒。但是cdn上面的地址确实多了一个1.

**Comment by webx32** [comment]
嗯 好吧 能用就行
